### ISSUE TITLE
Feature Required

### ISSUE THREAD

**Issue by amrmugl** [a5hk/night-coder#12]
Kindly add this line in {themes}.json files

` list.focusBackground: '#006600';`

It will provide a visual indicator when moving around using arrow keys in sidebar.

Whenever a new update comes it removes this line from theme settings.

**Comment by a5hk** [comment]
Thank you for opening the issue. I have updated the theme with that setting added.

By the way, if you want your customizations to persist across updates you can add those to your VS Code settings, eg:

```json
"workbench.colorCustomizations": {
    "[Night Coder*]": {
      "list.focusBackground": "#006600"
    }
}
```

**Comment by amrmugl** [comment]
Thank you for creating such an amazing theme :) i really love it!
