### ISSUE TITLE
Really nice theme but a different color for the sidebar would be better

### ISSUE THREAD

**Issue by max-programming** [a5hk/night-coder#2]
This theme got me love at first site lol. But it would be better if there could be a separate color for each section. 
![image](https://user-images.githubusercontent.com/51731966/82903581-ca7b5f00-9f7e-11ea-9276-2bfd4a7def06.png)

To differentiate the code section and the sidebar and terminal
KEEP IT UP

**Comment by a5hk** [comment]
Good suggestion. I will add a new variant to this theme with more contrasted sidebar and terminal, in a few days.

**Comment by max-programming** [comment]
Great! Now I will close this issue.

**Comment by a5hk** [comment]
I have added a new variant named Night Coder Contrast. It looks like this:

![contrast](https://user-images.githubusercontent.com/5412540/83037821-7e4d1f00-a051-11ea-8944-d48420492f94.png)
