### ISSUE TITLE
Colour for search input option buttons

### ISSUE THREAD

**Issue by seanh-canva** [a5hk/night-coder#23]
Love your theme. Small request is if the selected option (case sensitive opt in screenshot) can have a higher contract colour, similar / same as the hover colour (whole word opt in screenshot) that would be great.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/73509814/185539006-ed91d924-8bb4-4e52-8425-2387df281fde.png">

**Comment by a5hk** [comment]
Thanks for the feedback. Fixed in 4.3.2
