### ISSUE TITLE
Need a black theme

### ISSUE THREAD

**Issue by amugldx** [a5hk/night-coder#25]
I would like to get an addition of a complete black theme. All the other themes are good but they don't give a complete night vibe.
I've stumbled upon a good black theme but it lack some highlights. 

theme for some inspiration...
https://github.com/Rejdesu/purpleVoid

plus don't use too vivid colors, they tend to cause pain in the eyes.

https://github.com/moegi-design/vscode-theme
colors are good in this theme but they also lack highlights and full black vibe.

Thanks :)

**Comment by a5hk** [comment]
Hmmm, creating a complete black theme was what got me into theme creation in the first place! However, I eventually found less dark themes more interesting. 

I'll try to create one, but it will take some time.

**Comment by a5hk** [comment]
The new theme is named Charcoal. I hope you like it.

**Comment by amugldx** [comment]
I just checked it out. The colors are extremely dim. if you check the colors of purple void theme i linked above. It has got some beautiful colors. but on charcoal, its very hard to read code for me.

If you can change them, i'll be very happy. But if you can't i really appreciate the effort and work you put into this theme. Maybe someone else can like these colors. :)
